
export const recentVehiclesData = [
    {
        id: "1",
        title: "2021 BMW X5",
        stockId: "BDV12345",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80", // Replace with your image path
        status: "Live Auction",
        statusType: "live", 
        priceLabel: "Current Bid",
        price: "$28,500",
        timeLabel: "Ends In",
        timeValue: "1h 25m",
        views: "245",
    },
    {
        id: "2",
        title: "2019 Audi A6",
        stockId: "BDV12344",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Upcoming",
        statusType: "upcoming",
        priceLabel: "Starting Bid",
        price: "$18,000",
        timeLabel: "Starts In",
        timeValue: "2d 5h",
        views: "180",
    },
    {
        id: "3",
        title: "2020 Mercedes C300",
        stockId: "BDV12343",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Sold",
        statusType: "sold",
        priceLabel: "Sold Price",
        price: "$22,750",
        timeLabel: "Sold On",
        timeValue: "May 18, 2024",
        views: "320",
    },
    {
        id: "4",
        title: "2018 Toyota Camry",
        stockId: "BDV12342",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Draft",
        statusType: "draft",
        priceLabel: "Starting Bid",
        price: "$12,000",
        timeLabel: "Created On",
        timeValue: "May 19, 2024",
        views: "95",
    },
];