
export const recentVehiclesData = [
    {
        id: "1",
        title: "2021 BMW X5",
        stockId: "BDV12345",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80", // Replace with your image path
        status: "Live Auction",
        statusType: "live",
        priceLabel: "Current Bid",
        price: "$28,500",
        timeLabel: "Ends In",
        timeValue: "1h 25m",
        views: "245",
    },
    {
        id: "2",
        title: "2019 Audi A6",
        stockId: "BDV12344",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Upcoming",
        statusType: "upcoming",
        priceLabel: "Starting Bid",
        price: "$18,000",
        timeLabel: "Starts In",
        timeValue: "2d 5h",
        views: "180",
    },
    {
        id: "3",
        title: "2020 Mercedes C300",
        stockId: "BDV12343",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Sold",
        statusType: "sold",
        priceLabel: "Sold Price",
        price: "$22,750",
        timeLabel: "Sold On",
        timeValue: "May 18, 2024",
        views: "320",
    },
    {
        id: "4",
        title: "2018 Toyota Camry",
        stockId: "BDV12342",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        status: "Draft",
        statusType: "draft",
        priceLabel: "Starting Bid",
        price: "$12,000",
        timeLabel: "Created On",
        timeValue: "May 19, 2024",
        views: "95",
    },
];

export const myVehiclesData = [
    {
        id: "1",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        images: [
            { previewUrl: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-left-side-view.jpeg?isig=0&q=80" },
            { previewUrl: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-interior-dashboard.jpeg?isig=0&q=80" },
        ],
        name: "2021 BMW X5",
        vin: "VIN: 5UXCR6C07M9G12345",
        adminStatus: "pending", // 'pending' | 'approved' | 'rejected'
        auctionStatus: "draft", // 'draft' | 'upcoming' | 'live' | 'sold' | 'expired'
        status: { label: "Pending Approval", subtext: "Submitted on May 24, 2024", type: "pending", },
        auctionType: "Live Auction",
        bid: { amount: "$28,500", label: "Current Bid", },
        views: 245,
        timing: { date: "May 28, 2024", timeLeft: "in 1h 25m", statusColor: "text-amber-600", },
        action: { label: "View Details", type: "view", },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
    },
    {
        id: "2",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2019 Audi A6",
        vin: "VIN: WAUG8AFC1KN123456",
        adminStatus: "approved",
        auctionStatus: "upcoming",
        status: {
            label: "Upcoming",
            subtext: "Starts on May 26, 2024",
            type: "upcoming",
        },
        auctionType: "Live Auction",
        bid: {
            amount: "$18,000",
            label: "Starting Bid",
        },
        views: 180,
        timing: {
            date: "May 26, 2024",
            timeLeft: "in 2d 5h",
            statusColor: "text-blue-600",
        },
        action: {
            label: "View Details",
            type: "view",
        },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
        auctionStartDate: "May 24, 2024",
        auctionStartTime: "10:00 AM",
        auctionDuration: "7-days",
        auctionEndDateTime: "2024-05-31T10:00:00",
    },
    {
        id: "3",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2020 Mercedes C300",
        vin: "VIN: WDDWF8DB8LR123789",
        adminStatus: "approved",
        auctionStatus: "live",
        status: {
            label: "Live",
            subtext: "Ends on May 24, 2024",
            type: "live",
        },
        auctionType: "Live Auction",
        bid: {
            amount: "$22,750",
            label: "Current Bid",
        },
        views: 320,
        timing: {
            date: "May 24, 2024",
            timeLeft: "1h 10m left",
            statusColor: "text-red-500",
        },
        action: { label: "View Details", type: "view", },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
        auctionStartDate: "May 24, 2024",
        auctionStartTime: "10:00 AM",
        auctionDuration: "7-days",
        auctionEndDateTime: "2024-05-31T10:00:00",
        bidsList: [
            {
                id: "1",
                bidder: {
                    name: "John D.",
                    initials: "JD",
                    bidderId: "BD100245",
                },
                amount: "$32,000",
                bidTime: "May 24, 2024 at 10:28 AM",
                timeAgo: "2 minutes ago",
                status: "active",
                statusLabel: "Active",
                isHighestBid: true,
            },
            {
                id: "2",
                bidder: {
                    name: "Sarah K.",
                    initials: "SK",
                    bidderId: "BD100312",
                },
                amount: "$31,500",
                bidTime: "May 24, 2024 at 10:26 AM",
                timeAgo: "4 minutes ago",
                status: "outbid",
                statusLabel: "Outbid",
                isHighestBid: false,
            },
            {
                id: "3",
                bidder: {
                    name: "Mike L.",
                    initials: "ML",
                    bidderId: "BD100156",
                },
                amount: "$31,000",
                bidTime: "May 24, 2024 at 10:23 AM",
                timeAgo: "7 minutes ago",
                status: "outbid",
                statusLabel: "Outbid",
                isHighestBid: false,
            },
        ],
        watchersList: [
            {
                id: "1",
                name: "John D.",
                memberId: "MBD100245",
                avatar: "https://i.pravatar.cc/100?img=12",
                memberSince: "Apr 15, 2024",
                watchTime: "May 24, 2024 at 10:28 AM",
                timeAgo: "2 minutes ago",
            },
            {
                id: "2",
                name: "Sarah K.",
                memberId: "MBD100312",
                avatar: "https://i.pravatar.cc/100?img=47",
                memberSince: "Apr 18, 2024",
                watchTime: "May 24, 2024 at 10:26 AM",
                timeAgo: "4 minutes ago",
            },
            {
                id: "3",
                name: "Mike L.",
                memberId: "MBD100156",
                avatar: "https://i.pravatar.cc/100?img=33",
                memberSince: "Apr 10, 2024",
                watchTime: "May 24, 2024 at 10:23 AM",
                timeAgo: "7 minutes ago",
            },
        ],
    },
    {
        id: "4",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2018 Toyota Camry",
        vin: "VIN: 4T1B11HK5JU123456",
        adminStatus: "pending",
        auctionStatus: "draft",
        status: {
            label: "Draft",
            subtext: "Created on May 19, 2024",
            type: "draft",
        },
        auctionType: "Live Auction",
        bid: {
            amount: "—",
            label: "Not listed",
        },
        views: 95,
        timing: {
            date: "—",
            timeLeft: "",
            statusColor: "text-slate-400",
        },
        action: {
            label: "Continue",
            type: "continue",
        },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
    },
    {
        id: "5",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2022 Honda CR-V",
        vin: "VIN: 2HKRW1H86NH123456",
        adminStatus: "approved",
        auctionStatus: "sold",
        status: {
            label: "Sold",
            subtext: "Sold on May 15, 2024",
            type: "sold",
        },
        auctionType: "Live Auction",
        bid: {
            amount: "$24,000",
            label: "Sold Price",
        },
        views: 410,
        timing: {
            date: "May 15, 2024",
            timeLeft: "Completed",
            statusColor: "text-green-600",
        },
        action: {
            label: "View Details",
            type: "view",
        },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
    },
    {
        id: "6",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2021 Ford Explorer",
        vin: "VIN: 1FMSK8DH9MGC12345",
        adminStatus: "approved",
        auctionStatus: "sold",
        status: {
            label: "Sold",
            subtext: "Sold on May 10, 2024",
            type: "sold",
        },
        auctionType: "Buy Now",
        bid: {
            amount: "$29,500",
            label: "Sold Price",
        },
        views: 275,
        timing: {
            date: "May 10, 2024",
            timeLeft: "Completed",
            statusColor: "text-green-600",
        },
        action: {
            label: "View Details",
            type: "view",
        },
        description: 'Well-maintained vehicle in excellent condition with regular service history. The vehicle has been carefully used and is ready for its next owner.',
        titleStatus: 'Clean Title',
        driveType: 'All Wheel Drive (AWD)',
        accidentHistory: 'No Accidents Reported',
        engineSize: '2.0L',
        cylinders: 4,
        seats: '5 Seats',
        doors: '4 Doors',
        city: 'Dubai',
        emirate: 'Dubai',
    },
];

export const bidsData = [
    {
        id: "1",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2021 BMW X5",
        auctionStatus: "live",
        listingId: "BDV-2024-0021",
        vin: "5UXCR6C07M9G12345",
        bid: "$32,000",
        bidLabel: "Your Highest Bid",
        reserve: "$26,000",
        status: "highestBid",
        statusLabel: "Highest Bid",
        statusText: "You are currently the highest bidder",
        auctionEnds: "2d 14h 32m",
        date: "May 26, 2024",
        time: "at 10:30 AM",
        action: "View Auction",
    },

    {
        id: "2",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2019 Mercedes-Benz E-Class",
        auctionStatus: "upcoming",
        listingId: "BDV-2024-0017",
        vin: "WDDZF4KB6KA526735",
        bid: "$18,000",
        bidLabel: "Your Bid",
        reserve: "$15,000",
        status: "upcoming",
        statusLabel: "Upcoming",
        statusText: "Auction starts in 1d 05h",
        auctionEnds: "Starts in 1d 05h",
        date: "May 25, 2024",
        time: "at 10:00 AM",
        action: "View Details",
    },

    {
        id: "3",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2020 Audi Q7",
        auctionStatus: "upcoming",
        listingId: "BDV-2024-0012",
        vin: "WA1AHAF76LD012345",
        bid: "$24,000",
        bidLabel: "Your Bid",
        reserve: "$20,000",
        status: "upcoming",
        statusLabel: "Upcoming",
        statusText: "Auction starts in 3d 06h",
        auctionEnds: "Starts in 3d 06h",
        date: "May 27, 2024",
        time: "at 10:00 AM",
        action: "View Details",
    },

    {
        id: "4",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2018 Toyota Camry",
        auctionStatus: "ended",
        listingId: "BDV-2024-0008",
        vin: "4T1B11HK5JU123456",
        bid: "$16,500",
        bidLabel: "Your Final Bid",
        reserve: "$17,000",
        status: "outbid",
        statusLabel: "Outbid",
        statusText: "Winning bid: $17,200 by John D.",
        auctionEnds: "Ended",
        date: "May 20, 2024",
        time: "at 09:45 AM",
        action: "View Results",
    },

    {
        id: "5",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2021 Range Rover Sport",
        auctionStatus: "live",
        listingId: "BDV-2024-0025",
        vin: "SALWR2RU1MA123456",
        bid: "$55,000",
        bidLabel: "Your Highest Bid",
        reserve: "$50,000",
        status: "outbid",
        statusLabel: "Outbid",
        statusText: "Highest bid: $56,500 by Sarah K.",
        auctionEnds: "1d 02h 12m",
        date: "May 24, 2024",
        time: "at 11:00 AM",
        action: "View Auction",
    },

    {
        id: "6",
        image: "https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80",
        name: "2020 Ford F-150",
        auctionStatus: "ended",
        listingId: "BDV-2024-0005",
        vin: "1FTFW1ET7LFA12345",
        bid: "$28,000",
        bidLabel: "Your Final Bid",
        reserve: "$25,000",
        status: "won",
        statusLabel: "Won",
        statusText: "You won this auction",
        auctionEnds: "Ended",
        date: "May 18, 2024",
        time: "at 10:20 AM",
        action: "View Results",
    },
];

export const salesHistoryData = [
    {
        id: 'SL-2024-0028',
        vehicle: '2018 Toyota Camry',
        stockId: 'BDV12342',
        vehicleImage: 'https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80',
        buyerName: 'Robert Brown',
        buyerEmail: 'robert@example.com',
        saleDate: '30 May 2024',
        saleTime: '3:00 PM',
        salePrice: 12000,
        commissionRate: 5,
        commissionAmount: 600,
        payoutAmount: 11400,
        payoutDate: '30 May 2024',
        payoutTime: '3:00 PM',
        invoiceNo: 'INV-2024-0028',
        status: 'completed',
    },
    {
        id: 'SL-2024-0027',
        vehicle: '2022 Honda CR-V',
        stockId: 'BDV12341',
        vehicleImage: 'https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80',
        buyerName: 'Emily Davis',
        buyerEmail: 'emily@example.com',
        saleDate: '30 May 2024',
        saleTime: '3:00 PM',
        salePrice: 20500,
        commissionRate: 5,
        commissionAmount: 1025,
        payoutAmount: null, // not yet paid — must render as "—" in UI
        payoutDate: '30 May 2024',
        payoutTime: '3:00 PM',
        invoiceNo: 'INV-2024-0027',
        status: 'pending',
    },
    {
        id: 'SL-2024-0026',
        vehicle: '2021 Ford Explorer',
        stockId: 'BDV12340',
        vehicleImage: 'https://imgd.aeplcdn.com/370x208/n/cw/ec/225514/x5-exterior-right-side-view.jpeg?isig=0&q=80',
        buyerName: 'Michael Wilson',
        buyerEmail: 'michael@example.com',
        saleDate: '30 May 2024',
        saleTime: '3:00 PM',
        salePrice: 25000,
        commissionRate: 5,
        commissionAmount: 1250,
        payoutAmount: null,
        payoutDate: '30 May 2024',
        payoutTime: '3:00 PM',
        invoiceNo: 'INV-2024-0026',
        status: 'overdue', // included to test the 3rd status state — not in your original screenshot
    },

];

export const payoutsData = [
    {
        id: "PAYOUT12456",
        payoutDate: "May 31, 2024",
        payoutTime: "02:45 PM",
        earningsFrom: "May 1 - May 31, 2024",
        salesCount: "31 Sales",
        payoutMethod: "Bank Transfer",
        accountNumber: "**** 4567",
        amount: "$6,250.00",
        status: "Pending",
        statusSubtext: "Scheduled: Jun 3, 2024",
        referenceId: "UTR987654321"
    },
    {
        id: "PAYOUT12455",
        payoutDate: "May 15, 2024",
        payoutTime: "10:30 AM",
        earningsFrom: "Apr 16 - Apr 30, 2024",
        salesCount: "18 Sales",
        payoutMethod: "Bank Transfer",
        accountNumber: "**** 4567",
        amount: "$5,850.00",
        status: "Completed",
        statusSubtext: "Paid on May 15, 2024",
        referenceId: "UTR987123456"
    },
    {
        id: "PAYOUT12454",
        payoutDate: "Apr 30, 2024",
        payoutTime: "09:15 AM",
        earningsFrom: "Apr 1 - Apr 15, 2024",
        salesCount: "22 Sales",
        payoutMethod: "Bank Transfer",
        accountNumber: "**** 4567",
        amount: "$6,200.00",
        status: "Completed",
        statusSubtext: "Paid on Apr 30, 2024",
        referenceId: "UTR986654321"
    },
];