
import {
  LayoutDashboard, User, Users, Briefcase, Car,
  Gavel, HandCoins, ShieldAlert, FileText,
  BarChart3, Settings, Fingerprint, Cpu, MessageSquare
} from 'lucide-react';

export const dummyBuyers = [
  {
    id: "BUY-12456",
    name: "John Doe",
    username: "@johndoe",
    avatar: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "john.doe@gmail.com",
    emailVerified: true,
    phone: "+971 50 123 4567",
    phoneVerified: true,
    alternatePhone: "+971 56 987 6543",
    dob: "1990-04-15",
    gender: "Male",
    nationality: "United Arab Emirates",
    preferredLanguage: "English",
    address: "Al Barsha 1, Dubai, UAE",
    kycStatus: "verified",
    status: "active",
    joinedOn: "2024-05-12T10:30:00Z",
    lastActive: "2024-05-20T09:15:00Z",
    lastLogin: "2024-05-20T09:15:00Z",
    loginIP: "103.152.45.67",
    twoFAEnabled: true,
    emailNotifications: true,
    verifiedOn: "2024-05-13",
    idType: "Passport",
    idNumber: "A12345678",
    documentUrl: "#",
    wallet: { balance: 12450.00, pendingDeposits: 2300.00, totalSpent: 45750.00 },
    activities: [
      { id: 1, type: "bid", text: "Placed a bid on Toyota Land Cruiser", date: "2024-05-20T09:15:00Z" },
      { id: 2, type: "wallet", text: "Added funds to wallet", date: "2024-05-19T04:30:00Z" },
    ],
    activitySummary: { auctionsParticipated: 24, bidsPlaced: 15, auctionsWon: 5, auctionsLost: 3 },
    notes: [],
  },
  {
    id: "BUY-12456",
    name: "John Doe",
    username: "@johndoe",
    avatar: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "john.doe@gmail.com",
    phone: "+971 50 123 4567",
    kycStatus: "pending", // 'verified' | 'pending' | 'rejected'
    status: "active",       // 'active' | 'inactive' | 'suspended'
    joinedOn: "2024-05-12T10:30:00Z",
    lastActive: "2024-05-20T09:15:00Z",
  },
  {
    id: "BUY-12456",
    name: "John Doe",
    username: "@johndoe",
    avatar: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "john.doe@gmail.com",
    phone: "+971 50 123 4567",
    kycStatus: "rejected", // 'verified' | 'pending' | 'rejected'
    status: "inactive",       // 'active' | 'inactive' | 'suspended'
    joinedOn: "2024-05-12T10:30:00Z",
    lastActive: "2024-05-20T09:15:00Z",
  },
  {
    id: "BUY-12460",
    name: "David Lee",
    username: "@davidl",
    avatar: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "david.lee@gmail.com",
    phone: "+971 54 456 7890",
    kycStatus: "rejected",
    status: "suspended",
    joinedOn: "2024-05-07T03:45:00Z",
    lastActive: "2024-05-14T12:20:00Z",
  },
];

export const dummyStaff = [
  {
    id: 1,
    staffId: 'STF-1001',
    name: 'John Smith',
    username: 'john.smith',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Admin',
    department: 'Administration',
    email: 'john.smith@autobid.com',
    phone: '+971 50 123 4567',
    status: 'active',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'May 12, 2024, 10:30 AM',

    emailVerified: 'verified',
    phoneVerified: 'verified',

    dob: 'April 15, 1990',
    gender: 'Male',
    nationality: 'United Arab Emirates',
    alternatePhone: '+971 4 234 5678',
    idNumber: '784-1990-1234567-8',
    address: {
      street: 'Apartment 101, Al Barsha 1',
      city: 'Dubai',
      country: 'United Arab Emirates',
    },
    language: 'English',
    emergencyContact: {
      name: 'Sarah Smith',
      phone: '+971 55 987 6543',
    },

    employeeId: 'EMP-2024-1001',
    employmentType: 'Full Time',
    officeLocation: 'Dubai Head Office',
    reportingTo: 'Michael Brown (Manager)',
    payrollType: 'Salaried',
    workPhone: '+971 4 345 6789',

    passwordChangeDate: 'May 12, 2024',
    twoFactorEnabled: true,
    lastUpdatedOn: 'May 15, 2024, 04:20 PM',
  },
  {
    id: 2,
    staffId: 'STF-1002',
    name: 'Sarah Johnson',
    username: '@sarah.johnson',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Manager',
    department: 'Operations',
    email: 'sarah.j@autobid.com',
    phone: '+971 55 987 6543',
    status: 'active',
    lastLogin: 'Today, 08:45 AM',
    joinedOn: 'May 10, 2024, 02:15 PM',
  },
  {
    id: 3,
    staffId: 'STF-1003',
    name: 'Michael Brown',
    username: '@michael.brown',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Coordinator',
    department: 'Customer Support',
    email: 'michael.b@autobid.com',
    phone: '+971 52 345 6789',
    status: 'active',
    lastLogin: 'Yesterday, 06:20 PM',
    joinedOn: 'May 08, 2024, 09:10 AM',
  },
  {
    id: 4,
    staffId: 'STF-1004',
    name: 'Emily Davis',
    username: '@emily.davis',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Support',
    department: 'Customer Support',
    email: 'emily.d@autobid.com',
    phone: '+971 54 678 9012',
    status: 'active',
    lastLogin: 'Yesterday, 04:30 PM',
    joinedOn: 'May 05, 2024, 11:40 AM',
  },
  {
    id: 5,
    staffId: 'STF-1005',
    name: 'David Wilson',
    username: '@david.wilson',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Reviewer',
    department: 'Vehicle Inspection',
    email: 'david.w@autobid.com',
    phone: '+971 58 123 7890',
    status: 'active',
    lastLogin: 'May 19, 2024, 03:20 PM',
    joinedOn: 'May 03, 2024, 01:25 PM',
  },
  {
    id: 6,
    staffId: 'STF-1006',
    name: 'Jessica Taylor',
    username: '@jessica.taylor',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Content Editor',
    department: 'Content Management',
    email: 'jessica.t@autobid.com',
    phone: '+971 50 234 5678',
    status: 'inactive',
    lastLogin: 'May 15, 2024, 10:15 AM',
    joinedOn: 'Apr 28, 2024, 04:20 PM',
  },
  {
    id: 7,
    staffId: 'STF-1007',
    name: 'Robert Martinez',
    username: '@robert.martinez',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Finance Officer',
    department: 'Finance',
    email: 'robert.m@autobid.com',
    phone: '+971 56 789 0123',
    status: 'inactive',
    lastLogin: 'May 14, 2024, 02:40 PM',
    joinedOn: 'Apr 25, 2024, 11:05 AM',
  },
  {
    id: 8,
    staffId: 'STF-1008',
    name: 'William Anderson',
    username: '@william.anderson',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    role: 'Support',
    department: 'Customer Support',
    email: 'william.a@autobid.com',
    phone: '+971 52 987 6541',
    status: 'suspended',
    lastLogin: 'May 01, 2024, 09:10 AM',
    joinedOn: 'Apr 20, 2024, 09:00 AM',
  },
];

export const dummySeller = [
  {
    id: 1,
    sellerId: 'SLR-1001',
    name: 'Ahmed Al Mansoori',
    username: '@ahmed.mansoori',
    avatar: 'https://media.istockphoto.com/id/2151669184/vector/vector-flat-illustration-in-grayscale-avatar-user-profile-person-icon-gender-neutral.jpg?s=612x612&w=0&k=20&c=UEa7oHoOL30ynvmJzSCIPrwwopJdfqzBs0q69ezQoM8=',
    companyName: 'Gulf Motors Trading LLC',
    sellerType: 'Dealer',
    email: 'ahmed.m@gulfmotors.com',
    phone: '+971 50 111 2233',
    tradeLicenseStatus: 'verified',
    status: 'active',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'May 11, 2024, 10:00 AM',
    alternatePhone: "+971 50 111 2233",
    website: "http://.com",
    businessAddress: {
      street: "123 Business Bay, Office 404",
      city: "Dubai",
      country: "United Arab Emirates",
      zip: "00000"
    },
    socialMedia: {
      facebook: "facebook.com/mybusiness",
      instagram: "instagram.com/mybusiness",
      twitter: "twitter.com/mybusiness",
      linkedin: "linkedin.com/in/mybusiness"
    },
    vatNumber: "AE1234567890",
    establishedYear: 2015,
    numberOfEmployees: 25,
    preferredLanguage: "English",
    aboutBusiness: "We are a leading automotive dealership specializing in luxury and pre-owned vehicles with over a decade of trusted service.",
    tradeLicenseNumber: "TL-987654321",
    tradeLicenseExpiry: "2027-12-31",
    bankDetails: {
      bankName: "Emirates NBD",
      accountNumber: "100200300400",
      iban: "AE12 3456 7890 1234 5678 90",
      swiftCode: "ENBD AE DX",
      accountHolderName: "My Business Trading LLC"
    },
    kycStatus: "verified",
    verificationDate: "2024-05-12",
    lastVerifiedOn: "2026-01-15",
    nextKycDue: "2027-01-15",
    businessOverview: {
      totalListings: 150,
      activeListings: 45,
      soldVehicles: 105,
      totalSales: 4500000,
      totalBidsReceived: 890,
      responseRate: "98%"
    },
    rating: 4.8,
    reviewCount: 1240,

    kycDue: "15 May, 2024"
  },
  {
    id: 2,
    sellerId: 'SLR-1002',
    name: 'Fatima Hassan',
    username: '@fatima.hassan',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: 'Al Noor Auto Sales',
    sellerType: 'Dealer',
    email: 'fatima.h@alnoorauto.com',
    phone: '+971 55 222 3344',
    tradeLicenseStatus: 'verified',
    status: 'active',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'May 09, 2024, 01:30 PM',
  },
  {
    id: 3,
    sellerId: 'SLR-1003',
    name: 'Rashid Khoury',
    username: '@rashid.khoury',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: null, // individual seller — no company
    sellerType: 'Individual',
    email: 'rashid.k@gmail.com',
    phone: '+971 52 333 4455',
    tradeLicenseStatus: 'not_applicable',
    status: 'active',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'May 07, 2024, 09:15 AM',
  },
  {
    id: 4,
    sellerId: 'SLR-1004',
    name: 'Maria Santos',
    username: '@maria.santos',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: 'Premier Auto Group',
    sellerType: 'Dealer',
    email: 'maria.s@premierauto.com',
    phone: '+971 54 444 5566',
    tradeLicenseStatus: 'expired',
    status: 'inactive',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'Apr 30, 2024, 03:45 PM',
  },
  {
    id: 5,
    sellerId: 'SLR-1005',
    name: 'Omar Farouk',
    username: '@omar.farouk',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: null,
    sellerType: 'Individual',
    email: 'omar.f@gmail.com',
    phone: '+971 58 555 6677',
    tradeLicenseStatus: 'not_applicable',
    status: 'active',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'Apr 28, 2024, 11:20 AM',
  },
  {
    id: 6,
    sellerId: 'SLR-1006',
    name: 'Layla Ibrahim',
    username: '@layla.ibrahim',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: 'Emirates Fleet Solutions',
    sellerType: 'Dealer',
    email: 'layla.i@emiratesfleet.com',
    phone: '+971 50 666 7788',
    tradeLicenseStatus: 'pending',
    status: 'inactive',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'Apr 22, 2024, 02:00 PM',
  },
  {
    id: 7,
    sellerId: 'SLR-1007',
    name: 'Khalid Rahman',
    username: '@khalid.rahman',
    avatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    companyName: 'Al Falah Vehicle Trading',
    sellerType: 'Dealer',
    email: 'khalid.r@alfalahtrading.com',
    phone: '+971 56 777 8899',
    tradeLicenseStatus: 'verified',
    status: 'suspended',
    lastLogin: 'Today, 09:15 AM',
    joinedOn: 'Apr 18, 2024, 08:50 AM',
  },
];

// staff detail - permission tab
export const permissionsData = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: <LayoutDashboard size={16} className="text-gray-600" />,
    channels: { view: true, add: false, edit: false, delete: false, approve: null }
  },
  {
    id: 'user-management',
    label: 'User Management',
    icon: <User size={16} className="text-gray-600" />,
    channels: { view: true, add: true, edit: true, delete: false, approve: null },
    children: [
      {
        id: 'buyers',
        label: 'Buyers',
        icon: <Users size={16} className="text-gray-600" />,
        channels: { view: true, add: true, edit: true, delete: false, approve: null }
      },
      {
        id: 'sellers',
        label: 'Sellers',
        icon: <Users size={16} className="text-gray-600" />,
        channels: { view: true, add: true, edit: true, delete: false, approve: null }
      },
      {
        id: 'staff',
        label: 'Staff',
        icon: <User size={16} className="text-gray-600" />,
        channels: { view: true, add: true, edit: true, delete: false, approve: null }
      }
    ]
  },
  {
    id: 'vehicle-approvals',
    label: 'Vehicle Approvals',
    icon: <Car size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: null, delete: null, approve: true }
  },
  {
    id: 'auction-management',
    label: 'Auction Management',
    icon: <Gavel size={16} className="text-gray-600" />,
    channels: { view: true, add: true, edit: true, delete: false, approve: false }
  },
  {
    id: 'bid-management',
    label: 'Bid Management',
    icon: <HandCoins size={16} className="text-gray-600" />,
    channels: { view: true, add: true, edit: true, delete: false, approve: false }
  },
  {
    id: 'payment-management',
    label: 'Payment Management',
    icon: <Briefcase size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: true, delete: false, approve: null }
  },
  {
    id: 'dispute-management',
    label: 'Dispute Management',
    icon: <ShieldAlert size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: true, delete: false, approve: null }
  },
  {
    id: 'cms-management',
    label: 'CMS Management',
    icon: <FileText size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: null, delete: null, approve: null }
  },
  {
    id: 'reports',
    label: 'Reports & Analytics',
    icon: <BarChart3 size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: null, delete: null, approve: null }
  },
  {
    id: 'system-settings',
    label: 'System Settings',
    icon: <Settings size={16} className="text-gray-600" />,
    channels: { view: false, add: false, edit: false, delete: false, approve: false }
  },
  {
    id: 'kyc-verification',
    label: 'KYC Verification',
    icon: <Fingerprint size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: false, delete: false, approve: true }
  },
  {
    id: 'ai-features',
    label: 'AI & Advanced Features',
    icon: <Cpu size={16} className="text-gray-600" />,
    channels: { view: true, add: null, edit: null, delete: null, approve: null }
  },
  {
    id: 'live-chat',
    label: 'Live Chat',
    icon: <MessageSquare size={16} className="text-gray-600" />,
    channels: { view: true, add: true, edit: null, delete: null, approve: null }
  }
];

export const vehicleApproval = [
  {
    id: 1,
    vehicleDetails: {
      name: "2022 Toyota Land Cruiser",
      vin: "JTMCY7AJ8N4101234",
      type: "SUV",
      color: "White",
      transmission: "Automatic",
      imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg"
    },
    ownerSeller: {
      name: "James Wilson",
      bid: "BID-10023",
      email: "james.wilson@email.com",
      avatarUrl: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
    },
    submittedOn: "May 20, 2024",
    submittedDate: "09:15 AM",

    status: "Pending",

    documents: [
      { id: 1, name: "Vehicle Registration", description: "Registration Certificate (Mulkiya)", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 2, name: "Insurance Certificate", description: "Valid Vehicle Insurance", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 3, name: "Emirates ID (Owner)", description: "Owner Emirates ID Copy", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 4, name: "Driving License (Owner)", description: "Valid UAE Driving License", status: "Pending", fileUrl: "..." },
      { id: 5, name: "Vehicle Photos", description: "Front, Back, Both Sides & Interior", status: "Uploaded", fileUrl: "..." },
      { id: 6, name: "Vehicle Fitness Certificate", description: "RTA Fitness Certificate", status: "Pending", fileUrl: "..." },
      { id: 7, name: "Bank Loan Clearance (If any)", description: "No Objection Certificate from Bank", status: "Not Applicable", fileUrl: null },
      { id: 8, name: "Customs Clearance (If Imported)", description: "Customs Clearance Certificate", status: "Pending", fileUrl: "..." },
    ],
    history: [
      { id: 1, date: "May 20, 2024", time: "09:15 AM", action: "Request Submitted", description: "Vehicle approval request has been submitted by the seller.", performedBy: "James Wilson", role: "Seller", status: "Pending Review", remarks: "Initial request submitted." },
      { id: 2, date: "May 20, 2024", time: "09:18 AM", action: "Documents Uploaded", description: "All required documents have been uploaded.", performedBy: "James Wilson", role: "Seller", status: "Completed", remarks: "7 documents uploaded.", hasDocLink: true },
      { id: 3, date: "May 20, 2024", time: "09:25 AM", action: "Under Review", description: "Vehicle request is now under admin review.", performedBy: "Sarah Johnson", role: "Admin", status: "Under Review", remarks: "Documents are being verified." },
    ],
    notes: [
      {
        id: 1,
        author: "James Wilson",
        role: "Seller",
        message: "Hi, I have uploaded all the requested documents. Please let me know if anything is missing.",
        date: "May 20, 2024",
        time: "09:25 AM",
      },
      {
        id: 2,
        author: "Sarah Johnson",
        role: "Admin",
        message: "Please upload a valid Insurance Certificate. The current document is expired.",
        date: "May 20, 2024",
        time: "09:40 AM",
      },
    ]
  },
  {
    id: 2,
    vehicleDetails: {
      name: "2021 BMW 5 Series",
      vin: "WBA53BH06MCG12345",
      type: "Sedan",
      color: "Black",
      transmission: "Automatic",
      imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg"
    },
    ownerSeller: {
      name: "Sophia Brown",
      bid: "BID-10035",
      email: "sophia.brown@email.com",
      avatarUrl: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
    },

    submittedOn: "May 20, 2024",
    submittedDate: "09:15 AM",

    approvedOn: "May 20, 2024",
    approvedDate: "09:15 AM",
    approvedBy: "Admin",
    approvedUserImg: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",

    status: "Approved",

    documents: [
      { id: 1, name: "Vehicle Registration", description: "Registration Certificate (Mulkiya)", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 2, name: "Insurance Certificate", description: "Valid Vehicle Insurance", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 3, name: "Emirates ID (Owner)", description: "Owner Emirates ID Copy", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 4, name: "Driving License (Owner)", description: "Valid UAE Driving License", status: "Pending", fileUrl: "..." },
      { id: 5, name: "Vehicle Photos", description: "Front, Back, Both Sides & Interior", status: "Uploaded", fileUrl: "..." },
      { id: 6, name: "Vehicle Fitness Certificate", description: "RTA Fitness Certificate", status: "Pending", fileUrl: "..." },
    ],
    history: [
      { id: 1, date: "May 20, 2024", time: "09:15 AM", action: "Request Submitted", description: "Vehicle approval request has been submitted by the seller.", performedBy: "James Wilson", role: "Seller", status: "Pending Review", remarks: "Initial request submitted." },
      { id: 2, date: "May 20, 2024", time: "09:18 AM", action: "Documents Uploaded", description: "All required documents have been uploaded.", performedBy: "James Wilson", role: "Seller", status: "Completed", remarks: "7 documents uploaded.", hasDocLink: true },
      { id: 3, date: "May 20, 2024", time: "09:25 AM", action: "Under Review", description: "Vehicle request is now under admin review.", performedBy: "Sarah Johnson", role: "Admin", status: "Under Review", remarks: "Documents are being verified." },
    ],
    notes: [
      {
        id: 1,
        author: "James Wilson",
        role: "Seller",
        message: "Hi, I have uploaded all the requested documents. Please let me know if anything is missing.",
        date: "May 20, 2024",
        time: "09:25 AM",
      },
      {
        id: 2,
        author: "Sarah Johnson",
        role: "Admin",
        message: "Please upload a valid Insurance Certificate. The current document is expired.",
        date: "May 20, 2024",
        time: "09:40 AM",
      },
    ]
  },
  {
    id: 3,
    vehicleDetails: {
      name: "2020 Ford F-150",
      vin: "1FTEW1E50LFA12345",
      type: "Pickup",
      color: "Silver",
      transmission: "Automatic",
      imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg"
    },
    ownerSeller: {
      name: "Michael Davis",
      bid: "BID-10018",
      email: "michael.davis@email.com",
      avatarUrl: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
    },

    submittedOn: "May 20, 2024",
    submittedDate: "09:15 AM",

    approvedBy: "Admin",
    approvedUserImg: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",

    rejectedOn: "May 20, 2024",
    rejectedDate: "09:15 AM",
    rejectedReason: "Invalid Documents",

    status: "Rejected",

    documents: [
      { id: 1, name: "Vehicle Registration", description: "Registration Certificate (Mulkiya)", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 2, name: "Insurance Certificate", description: "Valid Vehicle Insurance", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 3, name: "Emirates ID (Owner)", description: "Owner Emirates ID Copy", status: "Pending", fileUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCGaWLzPWHCzPfAIjxaDNvMoA0Ddy9FeL7p0BaQR6CgQ&s=10" },
      { id: 4, name: "Driving License (Owner)", description: "Valid UAE Driving License", status: "Pending", fileUrl: "..." },
    ],
    history: [
      { id: 1, date: "May 20, 2024", time: "09:15 AM", action: "Request Submitted", description: "Vehicle approval request has been submitted by the seller.", performedBy: "James Wilson", role: "Seller", status: "Pending Review", remarks: "Initial request submitted." },
      { id: 2, date: "May 20, 2024", time: "09:18 AM", action: "Documents Uploaded", description: "All required documents have been uploaded.", performedBy: "James Wilson", role: "Seller", status: "Completed", remarks: "7 documents uploaded.", hasDocLink: true },
      { id: 3, date: "May 20, 2024", time: "09:25 AM", action: "Under Review", description: "Vehicle request is now under admin review.", performedBy: "Sarah Johnson", role: "Admin", status: "Under Review", remarks: "Documents are being verified." },
    ],
    notes: [
      {
        id: 1,
        author: "James Wilson",
        role: "Seller",
        message: "Hi, I have uploaded all the requested documents. Please let me know if anything is missing.",
        date: "May 20, 2024",
        time: "09:25 AM",
      },
      {
        id: 2,
        author: "Sarah Johnson",
        role: "Admin",
        message: "Please upload a valid Insurance Certificate. The current document is expired.",
        date: "May 20, 2024",
        time: "09:40 AM",
      },
    ]
  }
];

// all auction 
export const allAuctionData = [
  {
    id: "AUC-2024-00048",
    imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg",
    title: "2021 BMW X5 xDrive30i",
    vin: "WBABC3S0MCG12345",
    specs: {
      body: "SUV",
      color: "White",
      transmission: "Automatic",
      make: "Not Applicable",
      model: "xDrive40i",
      year: "2023",
      doors: "Not Applicable",
      seats: "Not Applicable",
      vehicleType: "Luxury SUV",
      engine: "Turbocharged Inline-6",
      engineSize: "3.0L",
      fuelType: "Petrol",
      cylinder: "6",
      driveType: "AWD",
      mileage: "14,500 km",
    },
    stockId: "AUC-2024-00048",
    seller: "John Motors FZ LLC",
    sellerVerified: true,
    fuelType: "Petrol",
    endsAt: "01:30 PM, May 20, 2024",

    type: "Standard",
    startTime: "10:00 AM",
    startDate: "May 20, 2024 ",
    endTime: "07:00 PM",
    endDate: "May 20, 2024 ",
    currentBid: "$28,500",
    reserve: "$25,000",
    bids: 23,
    bidders: 12,
    status: "Live",
    you: "you",

    timeLeft: "00 : 04 : 00",
    extended: "Extended +2 min",
    extensionRule: "2 minutes on last bid",
    startingBid: "$20,000",
    buyNowPrice: null,
    bidIncrement: "$250",
    description: "Very clean BMW X5 xDrive30i with low mileage. Full service history available. Single owner, accident free and ready to drive.",
    features: [
      "Panoramic sunroof",
      "Leather seats",
      "Navigation system",
      "360° camera",
      "Parking sensors",
    ],
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2024/8/444303282/EO/TR/EQ/3199782/car-carrier-trailer-500x500.jpg",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&q=80&w=600",
    ],
    documents: [
      {
        id: 1,
        name: "Registration Certificate.pdf",
        type: "Registration",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:15 AM",
        size: "245 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 2,
        name: "Insurance Document.pdf",
        type: "Insurance",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:16 AM",
        size: "320 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 3,
        name: "Inspection Report.pdf",
        type: "Inspection Report",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:17 AM",
        size: "512 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 4,
        name: "Service History.pdf",
        type: "Service History",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:18 AM",
        size: "410 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 5,
        name: "Front View.jpg",
        type: "Vehicle Image",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:19 AM",
        size: "1.2 MB",
        status: "Verified",
        fileType: "image",
      },
    ],
    participants: [
      {
        name: "Michael Davis",
        isYou: true,
        email: "michael.davis@email.com",
        phone: "+1 (408) 555-1234",
        date: "May 20, 2024",
        time: "12:45:20 PM",
        score: 12,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "John Smith",
        isYou: false,
        email: "john.smith@email.com",
        phone: "+1 (415) 555-5678",
        date: "May 20, 2024",
        time: "12:42:10 PM",
        score: 11,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "Sarah Johnson",
        isYou: false,
        email: "sarah.johnson@email.com",
        phone: "+1 (310) 555-8822",
        date: "May 20, 2024",
        time: "12:40:05 PM",
        score: 10,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "David Lee",
        isYou: false,
        email: "david.lee@email.com",
        phone: "+1 (214) 555-3344",
        date: "May 20, 2024",
        time: "12:38:50 PM",
        score: 9,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "Emma Wilson",
        isYou: false,
        email: "emma.wilson@email.com",
        phone: "+1 (602) 555-7788",
        date: "May 20, 2024",
        time: "12:37:15 PM",
        score: 8,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "Robert Johnson",
        isYou: false,
        email: "robert.j@email.com",
        phone: "+1 (773) 555-9011",
        date: "May 20, 2024",
        time: "12:36:02 PM",
        score: 7,
        status: "Active",
        verification: "Verified"
      }
    ],
    biddersData: [
      {
        id: 1,
        bidderName: "Michael Davis",
        isYou: true,
        totalBids: 12,
        bidAmount: "$28,500",
        isCurrentHighest: true,
        bidDate: "May 20, 2024",
        bidTime: "01:25:28 PM",
        bidType: "Manual Bid",
        status: "Active"
      },
      {
        id: 2,
        bidderName: "John Smith",
        isYou: false,
        totalBids: 11,
        bidAmount: "$28,000",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:22:34 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 3,
        bidderName: "Sarah Johnson",
        isYou: false,
        totalBids: 10,
        bidAmount: "$27,250",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:18:45 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 4,
        bidderName: "David Lee",
        isYou: false,
        totalBids: 9,
        bidAmount: "$26,500",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:15:09 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 6,
        rank: 6,
        bidderName: "Robert Johnson",
        isYou: false,
        totalBids: 7,
        bidAmount: "$25,000",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:10:30 PM",
        bidType: "Proxy Bid",
        status: "Outbid"
      },
    ],
    timeline: [
      { label: "Auction Created", date: "May 18, 2024", time: "09:00 AM", state: "completed" },
      { label: "Auction Started", date: "May 20, 2024", time: "10:00 AM", state: "completed" },
      { label: "Live Now", date: "May 20, 2024", time: "01:25 PM", state: "active" },
      { label: "Auction Ends", date: "May 20, 2024", time: "01:30 PM", state: "future" },
    ]
  },
  {
    id: "AUC-2024-00047",
    imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg",
    title: "2020 Mercedes-Benz C300",
    vin: "WDDWF8EB3LR123456",
    specs: {
      body: "SUV",
      color: "White",
      transmission: "Automatic",
      make: "Not Applicable",
      model: "xDrive40i",
      year: "2023",
      doors: "Not Applicable",
      seats: "Not Applicable",
      vehicleType: "Luxury SUV",
      engine: "Turbocharged Inline-6",
      engineSize: "3.0L",
      fuelType: "Petrol",
      cylinder: "6",
      driveType: "AWD",
      mileage: "14,500 km",
    },
    type: "Reserve",
    startTime: "10:00 AM",
    startDate: "May 20, 2024 ",
    endTime: "07:00 PM",
    endDate: "May 20, 2024 ",
    currentBid: "$19,750",
    reserve: "$20,000",
    bids: 15,
    bidders: 8,
    status: "Upcoming",

    startsIn: "Starts in 2 days",
    description: "Very clean BMW X5 xDrive30i with low mileage. Full service history available. Single owner, accident free and ready to drive.",
    features: [
      "Panoramic sunroof",
      "Leather seats",
      "Navigation system",
      "360° camera",
      "Parking sensors",
    ],
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2024/8/444303282/EO/TR/EQ/3199782/car-carrier-trailer-500x500.jpg",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&q=80&w=600",
    ],
    documents: [
      {
        id: 1,
        name: "Registration Certificate.pdf",
        type: "Registration",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:15 AM",
        size: "245 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 2,
        name: "Insurance Document.pdf",
        type: "Insurance",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:16 AM",
        size: "320 KB",
        status: "Verified",
        fileType: "pdf",
      },
      {
        id: 3,
        name: "Inspection Report.pdf",
        type: "Inspection Report",
        uploadedBy: "Seller",
        company: "John Motors FZ LLC",
        date: "May 18, 2024",
        time: "09:17 AM",
        size: "512 KB",
        status: "Verified",
        fileType: "pdf",
      },
    ],
    participants: [
      {
        name: "Michael Davis",
        isYou: true,
        email: "michael.davis@email.com",
        phone: "+1 (408) 555-1234",
        date: "May 20, 2024",
        time: "12:45:20 PM",
        score: 12,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "John Smith",
        isYou: false,
        email: "john.smith@email.com",
        phone: "+1 (415) 555-5678",
        date: "May 20, 2024",
        time: "12:42:10 PM",
        score: 11,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "Sarah Johnson",
        isYou: false,
        email: "sarah.johnson@email.com",
        phone: "+1 (310) 555-8822",
        date: "May 20, 2024",
        time: "12:40:05 PM",
        score: 10,
        status: "Active",
        verification: "Verified"
      },
      {
        name: "David Lee",
        isYou: false,
        email: "david.lee@email.com",
        phone: "+1 (214) 555-3344",
        date: "May 20, 2024",
        time: "12:38:50 PM",
        score: 9,
        status: "Active",
        verification: "Verified"
      },
    ],
    biddersData: [
      {
        id: 1,
        bidderName: "Michael Davis",
        isYou: true,
        totalBids: 12,
        bidAmount: "$28,500",
        isCurrentHighest: true,
        bidDate: "May 20, 2024",
        bidTime: "01:25:28 PM",
        bidType: "Manual Bid",
        status: "Active"
      },
      {
        id: 2,
        bidderName: "John Smith",
        isYou: false,
        totalBids: 11,
        bidAmount: "$28,000",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:22:34 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 3,
        bidderName: "Sarah Johnson",
        isYou: false,
        totalBids: 10,
        bidAmount: "$27,250",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:18:45 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 4,
        bidderName: "David Lee",
        isYou: false,
        totalBids: 9,
        bidAmount: "$26,500",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:15:09 PM",
        bidType: "Manual Bid",
        status: "Outbid"
      },
      {
        id: 5,
        bidderName: "Robert Johnson",
        isYou: false,
        totalBids: 7,
        bidAmount: "$25,000",
        isCurrentHighest: false,
        bidDate: "May 20, 2024",
        bidTime: "01:10:30 PM",
        bidType: "Proxy Bid",
        status: "Outbid"
      },
    ],
    timeline: [
      { label: "Auction Created", date: "May 10, 2024", time: "02:30 PM", state: "completed" },
      { label: "Vehicle Approved", date: "May 12, 2024", time: "11:15 AM", state: "completed" },
      { label: "Auction Scheduled", date: "May 15, 2024", time: "09:40 AM", state: "completed" },
      { label: "Auction Starts", date: "May 21, 2024", time: "10:00 AM", state: "future" },
    ]
  },
  {
    id: "AUC-2024-00046",
    imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg",
    title: "2019 Ford F-150 XLT",
    vin: "1FTFW1E50KFA12345",
    specs: {
      body: "Pickup",
      color: "Red",
      transmission: "Automatic"
    },
    type: "Standard",
    startTime: "10:00 AM",
    startDate: "May 20, 2024 ",
    endTime: "07:00 PM",
    endDate: "May 20, 2024 ",
    currentBid: "$22,300",
    reserve: "$18,000",
    bids: 18,
    bidders: 9,
    status: "Completed",
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2024/8/444303282/EO/TR/EQ/3199782/car-carrier-trailer-500x500.jpg",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&q=80&w=600",
    ],
  },
  {
    id: "AUC-2024-00044",
    imageUrl: "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg",
    title: "2022 Toyota RAV4 LE",
    vin: "JTMRFREV8ND123456",
    specs: {
      body: "SUV",
      color: "White",
      transmission: "Automatic"
    },
    type: "Standard",
    startTime: "10:00 AM",
    startDate: "May 20, 2024 ",
    endTime: "07:00 PM",
    endDate: "May 20, 2024 ",
    currentBid: "-",
    reserve: "$22,000",
    bids: 0,
    bidders: 0,
    status: "Cancelled",
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2024/8/444303282/EO/TR/EQ/3199782/car-carrier-trailer-500x500.jpg",
      "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&q=80&w=600",
    ],
  },
]